language: cpp
compiler:
 - gcc
 - clang


before_install:
  - echo "deb http://download.opensuse.org/repositories/home:/VPetya:/zorp/xUbuntu_12.04/ ./" | sudo tee -a /etc/apt/sources.list
  - wget -qO - http://download.opensuse.org/repositories/home:/VPetya:/zorp/xUbuntu_12.04/Release.key | sudo apt-key add -
  - sudo apt-get update -qq  
  - sudo apt-get install libboost-test-dev
  - wget http://cz.archive.ubuntu.com/ubuntu/pool/main/a/automake/automake1.4_1.4-p6-13.1_all.deb
  - wget http://cz.archive.ubuntu.com/ubuntu/pool/main/a/autoconf/autoconf_2.69-6_all.deb
  - sudo dpkg -i autoconf_2.69-6_all.deb
  - sudo dpkg -i automake1.4_1.4-p6-13.1_all.deb

script:
  - sudo apt-get install -qq devscripts equivs
  - sudo mk-build-deps -i
  - ./autogen.sh
  - ./configure
  - make
#  - make check


after_success:
  - dpkg-buildpackage -S
